name: Run Background Task

# The event that triggers the workflow; in this case, a schedule.
on:
  schedule:
    # CRON format: runs every day at 8:00 AM, 11:30 AM, and 4:00 PM UTC.
    - cron: '0 8,11,16 * * *'

jobs:
  run-background-task:
    runs-on: ubuntu-latest  # Use the latest Ubuntu virtual machine

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # Checks out your code

      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python environment
        with:
          python-version: '3.x'  # Specify the Python version to use (e.g., 3.8)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run the background task
        run: python main.py  # Runs your background script
